### ISSUE TITLE
ML-training-cost-calculator/docs/comms-guidelines.md fix

### ISSUE THREAD

**Issue by marko-polo-cheno** [aipaca-mlops/ML-training-cost-calculator#4]
https://github.com/aipaca-mlops/ML-training-cost-calculator/blob/d3a51ba4543dbcecfa27bfc8f67b5801199393e7/docs/comms-guidelines.md?plain=1#L15

``<INTERNAL TOOL>`` does not show up

**Comment by marko-polo-cheno** [comment]
![image](https://user-images.githubusercontent.com/37851975/171969464-12bb4962-e2fc-43f2-8184-71679ddaae4a.png)

**Comment by yuqil725** [comment]
This was a redundant item. I just deleted it. We don't have such a tool
